import matplotlib.pyplot as plt
import numpy as np
from py3Ddef import DeformationRun, BackgroundDeformation
from py3Ddef.geometry import discreteDislocation, UniformGrid
from py3Ddef.viewer import plotFault2D


# ================ py3Ddef example ================

# ---- Example of a discretized frictional vertical fault driven by a background
#      stress field with lithostatic pressure ----

# Context:  Similar to Ex08. The final solution is the same.
#           Here, the idea is to visualize the slip triggering effet
#           and instabilities of frictional dislocations.

# =================================================


# --- Medium parameters

nu = 0.25   # Poisson's ratio
E  = 7.e10  # Young's modulus (unit: Pa)
mu = 0.6    # coeff of internal friction

# --- Grid

# Minimal grid: we are focusing here only on the slip distribution on the dislocations
# not on the surrounding elastic medium.

nx = 1
ny = 1
nz = 1
grid = UniformGrid(1, 1, nx,\
                   1, 1, ny,\
                  -1,-1, nz)


# --- Background deformation

bg = BackgroundDeformation(bg_flag='stre',\
                        bg_field=np.array([0, 50e6, 0.0, 0, 0, 0.0, 0.0, 0.0, 0.0]))

# --- Dislocations geometry and boundary conditions

# fritional vertical strike-slip fault:
# ss = ds = ts = 0: no imposed stresses stored on the fault before the computation of the deformation
# fcode = 1 and sdrop = 1, frictional element and if failure, return to envelope
# C = 0, mu = 0.6, cohesion 0 Pa and coefficient of friction of 0.6
# rhoLitho = 3000 kg.m^{-3}: average rock density, used to compute the lithostatic pressure
# rhoFluid = 0 kg.m^{-3}: Density of the fluid: here no fluid
fault = discreteDislocation(x0=0, y0=0, z0=0, L=5, W=5, dip=90, strike=90, n_strike=20, n_dip=20, \
                            kode=2, ss=0, ds=0, ts=0, rhoLitho=3000, rhoFluid=0,\
                            fcode=1, sdrop=1, mu=0.6)


# --- Computation of 3D deformation

# We will visialize the triggering effect of slip on unstable dislocation up to 'maxiter' iteration before comparing with the final (converged solution).
maxiter  = 5

Di   = np.zeros((fault.nop,3), dtype=np.float64)
Dtot = np.zeros((fault.nop,3), dtype=np.float64)
for i in range(1,maxiter+1):

    solution = DeformationRun(grid=grid, patches=fault, nu=nu, mu=mu, E=E, bg=bg)
    solution.compute3Ddef(maxiter=i)

    # Unit of the output displacements: centimeters.
    solution.displ.rescale(1/100)   # conversion from cm to m
    solution.dislocs.rescale(1/100) # conversion from cm to m

    Dtot[:,0] = solution.d.us.copy()
    Dtot[:,1] = solution.d.ud.copy()
    Dtot[:,2] = solution.d.un.copy()
    
    Dtot = Dtot - Di

    Di[:,0] = solution.d.us.copy()
    Di[:,1] = solution.d.ud.copy()
    Di[:,2] = solution.d.un.copy()
    solution.dislocs.us = Dtot[:,0]
    solution.dislocs.ud = Dtot[:,1]
    solution.dislocs.un = Dtot[:,2]

    # --- Figure: slip on the fault

    # Make a mask 'patches2hatch' of the dislocations on the fault that are locked.
    mfault = solution.patches.group == fault.group_init
    locked = solution.d.norm[mfault] <= 0.001

    if i == 1:
        txt = 'Displacements generated by the dislocations initially\nfrictionally unstable due to the background stress field only'
    else:
        txt = 'Displacements induced at iteration %s by the triggering effect\nof the slip of dislocation during iteration %s'%(str(i),str(i-1))
    
    # Hatch the locked elements to highlight them: use the keyword argument 'patches2hatch'
    plotFault2D(fault, v=solution.d.norm, vec=solution.d, group=[fault.group_init], cmap=plt.cm.magma, vec_scale=None,
                patches2hatch=locked, vec_color='C0', cbar_title='|u| (m)', vmin=0, vmax=None,vec_width=3e-3,
                title=txt, center=False, figsize=(7,7))


# --- Final (converged) solution
solution = DeformationRun(grid=grid, patches=fault, nu=nu, mu=mu, E=E, bg=bg)
solution.compute3Ddef(maxiter=100)

# Unit of the output displacements: centimeters.
solution.displ.rescale(1/100)   # conversion from cm to m
solution.dislocs.rescale(1/100) # conversion from cm to m

# --- Figure: slip on the fault
mfault = solution.patches.group == fault.group_init
locked = solution.d.fstatus[mfault] == 0

plotFault2D(fault, v=solution.d.norm, vec=solution.d, group=[fault.group_init], cmap=plt.cm.magma, vec_scale=60,
            patches2hatch=locked, vec_color='C0', cbar_title='|u| (m)', vmin=0, vmax=None,vec_width=3e-3,
            title='Final converged displacement solution after %s iterations'%str(solution.niter), center=False, figsize=(7,7))


